include:
  - project: 'cokoapps/ci'
    ref: main
    file: 'ci-templates.yml'

variables:
  IMAGE_NAME_DEVELOPMENT: coko-org/products/ketty/ketty/root-development
  IMAGE_NAME_PREPRODUCTION_DEVELOP: ketty-client-ci-production-develop
  IMAGE_NAME_PREPRODUCTION_DEMO: ketty-client-ci-production-demo
  IMAGE_NAME_PRODUCTION_DEVELOP: ketty-client-deploy-develop
  IMAGE_NAME_PRODUCTION_DEMO: ketty-client
  IMAGE_NAME_STORYBOOK: ketty-client-storybook
  PATH_TO_BUILD: ./packages/client
  PATH_INSIDE_CONTAINER: /home/node/ketida
  COMPOSE_FILE_STORYBOOK: docker-compose.storybook-deploy.yml
  COMPOSE_FILE_DEPLOY_DEVELOP: docker-compose.develop-deploy.yml
  COMPOSE_FILE_DEPLOY_DEMO: docker-compose.demo-deploy.yml
  IMAGE_NAME_RELEASE_SERVER: cokoapps/ketty-server
  IMAGE_NAME_RELEASE_CLIENT: cokoapps/ketty-client

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'develop'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - Branch checks
  - Docs
  - Build development
  - Lint & Unit test
  - Deploy
  - Release
  - Publish

branch source and target rules:
  stage: Branch checks
  script:
    - if [[ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" == "main" ]]; then exit 1; fi # do not allow MRs from main into anything
    # - if [[ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" != "develop" && "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "main" ]]; then exit 1; fi # only develop can be merged into main
    - if [[ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" == "develop" && "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" != "main" ]]; then exit 1; fi # develop can only be merged into main

.pages:
  image: node:lts
  stage: Docs
  cache:
    paths:
      - node_modules/
  script:
    - cd docs
    - corepack enable
    - yarn install
    - yarn build
  artifacts:
    expire_in: 30min
    paths:
      - docs/build
  publish: docs/build
  only:
    - main

## LINT & UNIT TEST

.build development:
  stage: Build development
  interruptible: true
  image: docker:27
  services:
    - docker:27-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build
      --tag $CI_REGISTRY/$IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_REF_NAME.$CI_COMMIT_SHA
      -f Dockerfile .
    - docker push $CI_REGISTRY/$IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_REF_NAME.$CI_COMMIT_SHA

.lint:
  stage: Lint & Unit test
  interruptible: true
  image: $CI_REGISTRY/$IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_REF_NAME.$CI_COMMIT_SHA
  script:
    - cd /home/node/app
    - yarn coko-lint run

.unit test:
  extends: .client unit test
  stage: Lint & Unit test
  variables:
    IMAGE_NAME: $IMAGE_NAME_DEVELOPMENT
    WORKDIR: $PATH_INSIDE_CONTAINER

## E2E TESTS -- TO DO --
# NOTE: update 'needs' for publish stage after adding e2e tests.

## DEPLOY

.deploy develop:
  stage: Deploy
  image: cokoapps/fly
  only:
    - develop
  script:
    - cd ./packages/server
    - FLY_API_TOKEN=$FLY_TOKEN_SERVER_DEVELOP flyctl deploy -c ./fly-develop.toml --remote-only
    - cd ../client
    - FLY_API_TOKEN=$FLY_TOKEN_CLIENT_DEVELOP flyctl deploy -c ./fly-develop.toml --remote-only

.deploy main:
  stage: Deploy
  image: cokoapps/fly
  only:
    - main
  script:
    - cd ./packages/server
    - FLY_API_TOKEN=$FLY_TOKEN_SERVER_MAIN flyctl deploy -c ./fly-main.toml --remote-only
    - cd ../client
    - FLY_API_TOKEN=$FLY_TOKEN_CLIENT_MAIN flyctl deploy -c ./fly-main.toml --remote-only

## RELEASE

release:
  stage: Release
  interruptible: false
  image: node:20
  when: manual
  only:
    - main
  before_script:
    - git remote set-url --push origin "https://gitlab-ci-token:$CI_RELEASE_TOKEN@gitlab.coko.foundation/coko-org/products/ketty/ketty.git"
    - git config user.email "$CI_RELEASE_BOT_EMAIL"
    - git config user.name "ketty release bot"
  script:
    - node scripts/updatePackageJson.js
    - VERSION=$(node -e "const packageJson = require('./package.json'); console.log(packageJson.version);")
    - echo VERSION set to $VERSION
    - git add -A
    - git commit -m "release version $VERSION [skip ci]"
    - git show-ref --tags "$VERSION" > /dev/null 2>&1 && git tag -d "$VERSION" || echo "Tag '$VERSION' does not exist."
    - git tag $VERSION
    - git push origin HEAD:$CI_COMMIT_REF_NAME --verbose
    - git push origin $VERSION
    - echo RELEASE_VERSION=$VERSION >> version.env
  artifacts:
    reports:
      dotenv: version.env

publish server:
  stage: Publish
  interruptible: false
  image: docker:28
  services:
    - docker:28-dind
  needs:
    - release
  only:
    - main
  before_script:
    - '[ -z "$RELEASE_VERSION" ] && exit 1'
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - git fetch origin $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - cd packages/server
    - docker build --tag $IMAGE_NAME_RELEASE_SERVER:$RELEASE_VERSION -f Dockerfile-production .
    - docker push $IMAGE_NAME_RELEASE_SERVER:$RELEASE_VERSION

publish client:
  stage: Publish
  interruptible: false
  image: docker:28
  services:
    - docker:28-dind
  needs:
    - release
  only:
    - main
  before_script:
    - '[ -z "$RELEASE_VERSION" ] && exit 1'
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - git fetch origin $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - cd packages/client
    - docker build --tag $IMAGE_NAME_RELEASE_CLIENT:$RELEASE_VERSION -f Dockerfile-production .
    - docker push $IMAGE_NAME_RELEASE_CLIENT:$RELEASE_VERSION
